apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  serviceAccountName: jenkins
  containers:
    - name: docker
      image: docker:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
    - name: maven
      image: maven:3.8.6-openjdk-11
      command:
        - cat
      tty: true
      imagePullPolicy: Always
    - name: kubectl
      image: lachlanevenson/k8s-kubectl:latest
      command:
        - cat
      tty: true
      imagePullPolicy: Always
    - name: k6
      image: grafana/k6:latest
      command:
        - cat
      tty: true
      imagePullPolicy: Always

  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock