apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: back-end-deployment-blue
  namespace: p3-space
  labels: 
    app: e-commerce

spec: # Specifications for the Deployment!
  replicas: 1
  minReadySeconds: 25
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector: 
    matchLabels: 
      app: e-commerce
      color: blue
  template: 
    metadata: 
      labels: 
        app: e-commerce
        color: blue
    spec: # specification for the pod itself now!
      containers: 
        - name: back-end-deployment-blue
          image: elrintowser/p3-backend
          env:
            - name: DB_PLATFORM
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: DB_URL
              value: jdbc:postgresql://db-service.p3-space.svc.cluster.local:5432/postgres?user=postgres&password=example
            - name: DB_DRIVER
              value: org.postgresql.Driver
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "300Mi"
              cpu: "200m"