apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: p3-space
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/e-commerce/(.*)"
            backend:
              service:
                name: back-end-service
                port:
                  number: 5000
